name: Build



on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  linter:
    name: Linter
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2

      - name: Node.js Setup
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '14'
          cache: 'npm'

      - name: Installation of Node.js dependencies
        run: npm install

      - name: Lint
        run: npm run lint

  tests:
    needs: [linter]
    name: Tests
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2

      - name: Node.js Setup
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '14'
          cache: 'npm'

      - name: Installation of Node.js dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Generate Coverage
        run: npm run cover-report
        env:
          TZ: America/Sao_Paulo

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/lcov.info

  sonarcloud:
    name: SonarCloud
    needs: [linter, tests]
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
